name: CI

on:
  push:
    branches: [ "master" ]

env:
  GO_VERSION: 1.19.x
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # <account>/<repo>
  ENVIRONMENT_REPOSITORY: github.com/juanjoss/xconfig

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Install dependencies
        run: go mod tidy
        
      - name: Run tests
        run: |
          CGO_ENABLED=0 go test ./...

  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write # Used with sigstore/fulcio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Scan Docker image
        uses: azure/container-scan@v0
        with:
          image-name: ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      
      - name: Install cosign
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.11.0'
      
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
        
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout environment repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ENVIRONMENT_REPOSITORY }}
          ref: "master"
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      
      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2
        
      - name: Update kubernetes manifests
        run: |
          cd ./kustomize
          kustomize edit set image x-image:${{ github.repository }}:${{ needs.build.outputs.tags }}
          kustomize build . > ../manifests/x.yaml
          cat kustomization.yaml
          cd ..
      
      - name: Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "action@github.com"
          git status
          git add .
          git commit -m "Updating ${{ github.repository }} image tag to ${{ needs.build.outputs.tags }}"
          git push origin master
